# Compute work centroids and 93% confidence radii
# given a reference_embeddings.pkl created by make_embeds.
# First draft by Claude Sonnet 4.5 2024-12-08, prompted by alanngnet

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Compute work centroids from a reference_embeddings.pkl file.

The centroids file is the deployment unit for inference: tools.identify
consumes it directly. It can be shipped to end-user devices for local inference
without the (much larger) reference embeddings file. All metadata required for
calibrated, fingerprint-checked inference is copied into the centroids
file at compute time.

Geometry: assumes unit-normalized input embeddings (the standard output
of the current tools.make_embeds). Centroids are computed by spherical
mean - take the mean of unit perfs, then re-normalize to the unit
hypersphere. This makes radii (angular spread) and query-time cosine
distances live in the same geometry. The pre-renormalization magnitude
is retained as a coherence scalar in [0, 1]: 1 = all perfs of this work
point identically, 0 = perfs maximally spread.

Radii: mean + 1.5 * std of within-work cosine distance from the
spherical-mean centroid. Captures ~93% of perfs assuming a roughly
Gaussian within-work distribution. Used downstream as a confidence
filter in tools.identify.

Example invocation:
    python -m tools.compute_centroids \\
        data/covers80/reference_embeddings.pkl \\
        data/covers80/work_centroids.pkl

[NOT YET IMPLEMENTED FOR A PRODUCTION ENVIRONMENT:] Optional --export-edge 
writes a packed-binary deployment artifact alongside the pkl, suitable for 
edge devices:
    python -m tools.compute_centroids \\
        data/covers80/reference_embeddings.pkl \\
        data/covers80/work_centroids.pkl \\
        --export-edge data/covers80/centroids_edge.npz

Output schema (pkl):
    {
        "centroids":          dict work_id -> unit np.ndarray (float32)
        "radii":              dict work_id -> float (angular)
        "coherence":          dict work_id -> float in [0, 1]
        "work_to_perfs":      dict work_id -> list of perf_ids
        "normalized":         True
        "embed_dim":          int
        "model_fingerprint":  str (16 hex, copied from embeddings file)
        "calibration":        dict per src.calibration schema (copied)
    }

@author: alanngnet with Claude
Originally created 2024-12-08 by alanngnet with Claude Sonnet 4.5. This version
used the not-normalized raw embeddings generated by the old make_embeds.

Completely rewritten 2026-05-03 by alanngnet with Claude Opus 4.7. This version 
was needed to use the new normalized embeddings generated by the new make_embeds,
and to improve accuracy in downstream end-user CSI applications.

"""

import argparse
import pickle
import sys

import numpy as np
from collections import defaultdict

from src.utils import load_reference_embeddings


def compute_centroids(embeddings_path: str, output_path: str) -> dict:
    """Compute work centroids from a reference_embeddings.pkl file.

    Returns the record that was written, for the convenience of any
    caller that wants to inspect it without re-loading.
    """
    record = load_reference_embeddings(embeddings_path)

    if not record["normalized"]:
        raise ValueError(
            f"{embeddings_path} contains raw (un-normalized) embeddings. "
            f"compute_centroids requires unit-normalized input. "
            f"Regenerate without --raw, or write your own raw-space "
            f"centroid script for research use."
        )

    embeddings = record["embeddings"]
    embed_dim = record["embed_dim"]
    fingerprint = record["model_fingerprint"]
    calibration = record["calibration"]

    if calibration is None:
        # Should not happen for normalized embeddings, but guard anyway
        # so the failure mode is loud rather than silently shipping a
        # centroids file with no calibration to downstream inference.
        raise ValueError(
            f"{embeddings_path} has no calibration record. The centroids "
            f"file would be unusable for confidence reporting. "
            f"Regenerate the embeddings file."
        )

    # Group performances by work using the perf_id naming convention.
    work_to_perfs = defaultdict(list)
    for perf_id in embeddings:
        work_id = perf_id.split(".")[0]
        work_to_perfs[work_id].append(perf_id)

    centroids = {}
    radii = {}
    coherence = {}

    print(f"Computing centroids for {len(work_to_perfs)} works...")
    for work_id, perf_ids in work_to_perfs.items():
        # Stack this work's unit perfs as (n_perfs, D).
        # Inputs are already unit-normalized at storage time.
        perf_matrix = np.stack(
            [embeddings[pid] for pid in perf_ids], axis=0
        ).astype(np.float64)
        # Sanity check on input geometry; cheap and fails loud if a
        # caller has fed in something we don't support.
        input_norms = np.linalg.norm(perf_matrix, axis=1)
        if not np.allclose(input_norms, 1.0, atol=1e-4):
            raise ValueError(
                f"Work {work_id}: input embeddings are not unit-normalized "
                f"(norm range {input_norms.min():.4f} to "
                f"{input_norms.max():.4f}). The reference_embeddings.pkl "
                f"is corrupt or was written by an incompatible version."
            )

        # Spherical mean: arithmetic mean of unit vectors, then re-norm.
        # The pre-renorm magnitude is the coherence scalar.
        mean_vec = perf_matrix.mean(axis=0)
        magnitude = float(np.linalg.norm(mean_vec))

        if magnitude < 1e-8:
            # Degenerate: perfs cancel out (would happen if a work's
            # perfs were arranged antipodally, which shouldn't occur in
            # CSI data but we guard anyway). Fall back to first perf as
            # centroid; coherence is recorded as 0 to flag the work.
            print(
                f"Warning: work {work_id} has near-zero spherical-mean "
                f"magnitude ({magnitude:.2e}); centroid is ill-defined. "
                f"Using first perf as fallback."
            )
            centroid = perf_matrix[0].copy()
            magnitude = 0.0
        else:
            centroid = mean_vec / magnitude

        centroids[work_id] = centroid.astype(np.float32)
        coherence[work_id] = magnitude

        # Radius: angular distance of each perf from the spherical-mean
        # centroid. Both sides unit-norm so cosine distance reduces to
        # 1 - dot product.
        dots = perf_matrix @ centroid
        dots = np.clip(dots, -1.0, 1.0)
        distances = 1.0 - dots
        radii[work_id] = float(distances.mean() + 1.5 * distances.std())

    out_record = {
        "centroids": centroids,
        "radii": radii,
        "coherence": coherence,
        "work_to_perfs": dict(work_to_perfs),
        "normalized": True,
        "embed_dim": embed_dim,
        "model_fingerprint": fingerprint,
        "calibration": calibration,
    }

    with open(output_path, "wb") as f:
        pickle.dump(out_record, f)

    # Reporting: a quick sanity summary so the user can spot anomalies.
    radii_arr = np.array(list(radii.values()))
    coh_arr = np.array(list(coherence.values()))
    print(
        f"Saved centroids for {len(centroids)} works to {output_path}\n"
        f"  Radii:     median={np.median(radii_arr):.4f}  "
        f"min={radii_arr.min():.4f}  max={radii_arr.max():.4f}\n"
        f"  Coherence: median={np.median(coh_arr):.4f}  "
        f"min={coh_arr.min():.4f}  max={coh_arr.max():.4f}\n"
        f"  Fingerprint: {fingerprint}"
    )

    return out_record


def export_edge(record: dict, output_path: str) -> None:
    """Write a packed-binary deployment artifact for edge devices.

    Loses the work_to_perfs mapping (not needed for query-time lookup)
    and stores the centroids as parallel arrays rather than a dict, for
    fast batch loading and small footprint. Format is .npz; future
    iterations may move to a custom packed binary if file size becomes
    critical for browser delivery.

    Schema:
        work_ids:          (N,) array of str (object dtype)
        centroids:         (N, D) float32
        radii:             (N,) float32
        coherence:         (N,) float32
        embed_dim:         scalar
        model_fingerprint: scalar str
        calibration_*:     calibration record fields, individually
    """
    work_ids = list(record["centroids"].keys())
    n = len(work_ids)
    d = record["embed_dim"]

    centroids_arr = np.empty((n, d), dtype=np.float32)
    radii_arr = np.empty(n, dtype=np.float32)
    coh_arr = np.empty(n, dtype=np.float32)
    for i, wid in enumerate(work_ids):
        centroids_arr[i] = record["centroids"][wid]
        radii_arr[i] = record["radii"][wid]
        coh_arr[i] = record["coherence"][wid]

    cal = record["calibration"]
    np.savez_compressed(
        output_path,
        work_ids=np.array(work_ids, dtype=object),
        centroids=centroids_arr,
        radii=radii_arr,
        coherence=coh_arr,
        embed_dim=np.int32(d),
        model_fingerprint=record["model_fingerprint"],
        cal_mu=np.float32(cal["mu"]),
        cal_sigma=np.float32(cal["sigma"]),
        cal_ecdf_quantiles=cal["ecdf_quantiles"],
        cal_ecdf_probs=cal["ecdf_probs"],
        cal_n_pairs=np.int32(cal["n_pairs"]),
        cal_n_quantiles=np.int32(cal["n_quantiles"]),
    )
    print(f"Edge artifact written to {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Compute work centroids from reference embeddings."
    )
    parser.add_argument(
        "embeddings_path",
        help="Path to reference_embeddings.pkl from tools.make_embeds.",
    )
    parser.add_argument(
        "output_path",
        help="Path to write the centroids pkl file.",
    )
    parser.add_argument(
        "--export-edge",
        type=str,
        default=None,
        metavar="PATH",
        help="Also write a packed-binary deployment artifact at PATH "
        "(e.g. centroids_edge.npz) suitable for edge inference.",
    )
    args = parser.parse_args()

    record = compute_centroids(args.embeddings_path, args.output_path)

    if args.export_edge:
        export_edge(record, args.export_edge)

    sys.exit(0)
