
#!/usr/bin/env python3
"""
Command-line utility to identify the closest matches to a query audio
recording from within a trained model's reference set of embeddings.

Assumptions:
    Query audio duration < chunk_s (default = 135 sec).
    You already trained your model.
    You already ran tools.make_embeds, and (if using -centroids)
        tools.compute_centroids.

Example:
    python -m tools.identify data/covers80 training/covers80 query.wav -top=10

Centroids mode (work-level matching):
    python -m tools.identify data/covers80 training/covers80 query.wav \\
        -top=10 -centroids

Calibrated scoring (z-score and p-value next to raw cosine distance):
    python -m tools.identify data/covers80 training/covers80 query.wav \\
        -top=10 --calibrated

Save the query embedding (always unit-normalized):
    python -m tools.identify data/covers80 training/covers80 query.wav \\
        -save query.npy

Parameters
----------
data_path : path to the folder containing reference_embeddings.pkl and,
    optionally, work_centroids.pkl. Both must have been built against
    the same model checkpoint as model_path (verified by fingerprint).

model_path : path to the folder containing config/hparams.yaml and a
    checkpoints/ subfolder.

query_path : path to the query audio file.

-top : N (default 10). Number of closest matches to return.

-centroids : if set, match against work centroids (one entry per work)
    rather than per-performance embeddings. Required for confidence-
    radius filtering.

--calibrated : if set, display z-score and p-value alongside raw cosine
    distance. Calibrated scoring is what to use for cross-model
    comparisons or for displaying confidence to end users.

-save : optional path to save the (unit-normalized) query embedding.

Originally created on Sat Mar  2 17:31:23 2024 
@author: alanngnet with ChatGPT

Completely rewritten 2026-05-03 by alanngnet with Claude Opus 4.7 to use the
new normalized embeddings generated by the revised make_embeds and 
compute_centroids tools.

"""

import argparse
import os

import numpy as np
import torch
from nnAudio.features.cqt import CQT, CQT2010v2
from tabulate import tabulate

from src.calibration import pvalue, z_score
from src.cqt import shorter
from src.model import Model
from src.utils import (
    compute_model_fingerprint,
    load_centroids,
    load_hparams,
    load_reference_embeddings,
)


def _make_feat(wav_path, fmin, max_freq, n_bins, bins_per_octave, device):
    """
    Borrowed CQT logic from tools.extract_csi_features
        _extract_cqt_worker_torchaudio()
    This function should stay synchronized with that one.
    """
    import librosa

    # CQT seems faster on mps, and CQT2010v2 faster on cuda
    if device == "mps":
        transform = CQT
    elif device == "cuda":
        transform = CQT2010v2

    # Load audio using librosa and force sample rate of 16kHz
    signal, sr = librosa.load(wav_path, sr=16000, mono=True)

    # Convert to torch tensor and move to device
    signal = torch.from_numpy(signal).float().unsqueeze(0).to(device)

    signal = (
        signal
        / torch.max(
            torch.tensor(0.001).to(device), torch.max(torch.abs(signal))
        )
        * 0.999
    )
    signal = transform(
        16000,
        hop_length=640,
        n_bins=n_bins,
        fmin=fmin,
        bins_per_octave=bins_per_octave,
        verbose=False,
    ).to(device)(signal)
    signal = signal + 1e-9
    signal = signal.squeeze(0)

    # Add contrast
    ref_value_log10 = torch.log10(torch.max(signal))
    signal = 20 * torch.log10(signal) - 20 * ref_value_log10

    signal = torch.swapaxes(signal, 0, 1)
    cqt = signal.numpy(force=True)
    return cqt


def _get_feat(query_path, data_hp, chunk_len, mean_size):
    """
    adapted from dataset.py AudioFeatDataset::__getitem__()
    assumes "mode" = "defined" and start = 0
    """
    if "bins_per_octave" not in data_hp:
        bins_per_octave = 12
    else:
        bins_per_octave = data_hp["bins_per_octave"]
    max_freq = data_hp["fmin"] * (2 ** (data_hp["n_bins"] / bins_per_octave))
    feat = _make_feat(
        query_path,
        data_hp["fmin"],
        max_freq,
        data_hp["n_bins"],
        bins_per_octave,
        data_hp["device"],
    )
    feat = feat[0:chunk_len]
    if len(feat) < chunk_len:
        feat = np.pad(
            feat,
            pad_width=((0, chunk_len - len(feat)), (0, 0)),
            mode="constant",
            constant_values=-100,
        )
    feat = shorter(feat, mean_size)
    return torch.from_numpy(feat)


def _build_reference_matrix(record_or_centroids, mode):
    """Stack the embedding dict into a contiguous (N, D) float32 matrix
    plus a parallel labels list, for vectorized distance computation.

    Args:
        record_or_centroids: the loaded embeddings record (perf mode) or
            centroids record (centroids mode).
        mode: "perf" or "centroids".

    Returns:
        (matrix, labels, radii_arr)
        radii_arr is None in perf mode.
    """
    if mode == "centroids":
        emb_dict = record_or_centroids["centroids"]
        radii_dict = record_or_centroids["radii"]
    else:
        emb_dict = record_or_centroids["embeddings"]
        radii_dict = None

    labels = list(emb_dict.keys())
    n = len(labels)
    if n == 0:
        raise ValueError("Reference set is empty.")
    d = emb_dict[labels[0]].shape[0]
    matrix = np.empty((n, d), dtype=np.float32)
    for i, label in enumerate(labels):
        matrix[i] = emb_dict[label]

    radii_arr = None
    if radii_dict is not None:
        radii_arr = np.array(
            [radii_dict[label] for label in labels], dtype=np.float32
        )

    return matrix, labels, radii_arr


def _verify_fingerprint(model_fingerprint, ref_record, centroids_record):
    """Cross-check that the embeddings, centroids (if any), and live
    model all derive from the same trained weights. Failure is loud
    rather than silent because mismatched files yield meaningless
    matches, not visibly broken ones."""
    ref_fp = ref_record["model_fingerprint"]
    if ref_fp != model_fingerprint:
        raise RuntimeError(
            f"Fingerprint mismatch: live model is {model_fingerprint}, "
            f"reference embeddings were built with {ref_fp}. "
            f"Regenerate reference_embeddings.pkl, or load the matching "
            f"checkpoint."
        )
    if centroids_record is not None:
        cen_fp = centroids_record["model_fingerprint"]
        if cen_fp != model_fingerprint:
            raise RuntimeError(
                f"Fingerprint mismatch: live model is {model_fingerprint}, "
                f"centroids were built with {cen_fp}. Regenerate "
                f"work_centroids.pkl."
            )


def _main():
    parser = argparse.ArgumentParser(
        description="Identify closest matches to a query audio recording."
    )
    parser.add_argument("data_path")
    parser.add_argument("model_path")
    parser.add_argument("query_path")
    parser.add_argument("-top", type=int, default=10)
    parser.add_argument(
        "-centroids",
        action="store_true",
        help="Match against work centroids rather than perfs.",
    )
    parser.add_argument(
        "--calibrated",
        action="store_true",
        help="Display z-score and p-value alongside cosine distance.",
    )
    parser.add_argument(
        "-save",
        type=str,
        default=None,
        help="Save the (normalized) query embedding to this path.",
    )
    args = parser.parse_args()

    data_dir = args.data_path
    model_dir = args.model_path

    # -------- Load hparams --------
    data_hp = load_hparams(os.path.join(data_dir, "hparams.yaml"))
    model_hp = load_hparams(os.path.join(model_dir, "config/hparams.yaml"))

    # Auto-detect optimal inference device (independent of training device)
    if torch.backends.mps.is_available():
        device = torch.device("mps")
        model_hp["device"] = "mps"
        data_hp["device"] = "mps"
    elif torch.cuda.is_available():
        device = torch.device("cuda")
        model_hp["device"] = "cuda"
        data_hp["device"] = "cuda"
    else:
        device = torch.device("cpu")
        model_hp["device"] = "cpu"
        data_hp["device"] = "cpu"

    # -------- Load reference data, verify fingerprints --------
    ref_record = load_reference_embeddings(
        os.path.join(data_dir, "reference_embeddings.pkl")
    )
    centroids_record = None
    if args.centroids:
        centroids_record = load_centroids(
            os.path.join(data_dir, "work_centroids.pkl")
        )

    if not ref_record["normalized"]:
        raise RuntimeError(
            "tools.identify requires normalized reference embeddings; "
            "this file was built with --raw. Regenerate without --raw."
        )

    calibration = ref_record["calibration"]
    if args.calibrated and calibration is None:
        raise RuntimeError(
            "--calibrated requested but reference embeddings have no "
            "calibration record. Regenerate without --raw."
        )

    # -------- Generate query embedding --------
    if isinstance(model_hp["chunk_frame"], list):
        infer_frame = model_hp["chunk_frame"][0] * model_hp["mean_size"]
    else:
        infer_frame = model_hp["chunk_frame"] * model_hp["mean_size"]
    chunk_s = model_hp["chunk_s"]
    assert (
        infer_frame == chunk_s * 25
    ), f"Error for mismatch of chunk_frame and chunk_s: {infer_frame}!={chunk_s}*25"

    query_feat = _get_feat(
        args.query_path, data_hp, infer_frame, model_hp["mean_size"]
    ).unsqueeze(0).to(device)

    with torch.no_grad():
        model = Model(model_hp).to(device)
        model.eval()
        checkpoint_dir = os.path.join(model_dir, "checkpoints")
        model.load_model_parameters(checkpoint_dir, device=device)

        # Fingerprint check happens after weights are loaded, so we hash
        # what's actually in memory.
        live_fingerprint = compute_model_fingerprint(model.state_dict())
        _verify_fingerprint(live_fingerprint, ref_record, centroids_record)

        query_embed, _ = model.inference(query_feat)
    query_embed = query_embed.cpu().numpy()[0].astype(np.float32)

    # Normalize the query (reference is already unit-norm). Guard
    # against degenerate zero-norm output.
    q_norm = float(np.linalg.norm(query_embed))
    if q_norm == 0.0:
        raise RuntimeError(
            "Query produced a zero-norm embedding. Audio may be silent "
            "or otherwise pathological."
        )
    query_unit = query_embed / q_norm

    if args.save:
        np.save(args.save, query_unit)
        print(f"Query embedding saved to: {args.save}")

    # -------- Vectorized distance computation --------
    mode = "centroids" if args.centroids else "perf"
    ref_matrix, labels, radii_arr = _build_reference_matrix(
        centroids_record if args.centroids else ref_record, mode
    )

    # All vectors unit-norm: cosine distance = 1 - dot product.
    # Single matrix-vector product replaces the per-label scipy.cosine
    # loop in the old code.
    dots = ref_matrix @ query_unit
    np.clip(dots, -1.0, 1.0, out=dots)
    distances = 1.0 - dots

    # -------- Optional radius filtering (centroids mode) --------
    if args.centroids:
        # Filter by calibrated p-value rather than per-work radius.
        # A radius-based filter on training-set within-work spread
        # systematically rejects legitimate held-out queries because
        # the model overfits same-label distances during training.
        # The negative distribution captured at calibration time is
        # the right reference: reject only if the query's distance is
        # plausible under "unrelated tunes."
        p_threshold = 0.001  # tunable; ~z < -3, conservative match floor
        pvals = pvalue(distances, calibration)
        mask = pvals < p_threshold
        if not mask.any():
            print(
                "\nNo matches found below "
                f"p-value threshold {p_threshold}."
            )
            return [], [], None
        distances = np.where(mask, distances, np.inf)

    # -------- Top-N selection --------
    top = min(args.top, len(labels))
    top_idx = np.argpartition(distances, top - 1)[:top]
    top_idx = top_idx[np.argsort(distances[top_idx])]
    # Drop any infinities from the radius mask (in case top > #matches).
    top_idx = [i for i in top_idx if np.isfinite(distances[i])]

    top_labels = [labels[i] for i in top_idx]
    top_distances = distances[top_idx]

    # -------- Calibrated scoring (optional) --------
    scored = None
    if args.calibrated:
        z = z_score(top_distances, calibration)
        p = pvalue(top_distances, calibration)
        scored = list(zip(top_labels, top_distances, z, p))

    return top_labels, top_distances, scored


if __name__ == "__main__":
    labels, distances, scored = _main()
    if scored is not None:
        rows = [
            (lab, f"{d:.4f}", f"{z:+.2f}", f"{p:.2e}")
            for lab, d, z, p in scored
        ]
        print(
            tabulate(
                rows,
                headers=["Label", "Distance", "Z-score", "P-value"],
                tablefmt="grid",
            )
        )
    else:
        rows = list(zip(labels, [f"{d:.4f}" for d in distances]))
        print(
            tabulate(
                rows, headers=["Label", "Distance"], tablefmt="grid"
            )
        )